on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 19.8.1
      uses: actions/setup-node@v2
      with:
        node-version: '19.8.1'
      
    - name: 🔨 Build Project
      run: |
        pwd
        ls -ltra
        npm install
        npm run build
    
    - name: List output files
      run: find build/ -print
      
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ftp.redes.la
        username: sikuapp@giacomo.one
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        
